# Generated by Django 3.0.6 on 2020-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заглавие')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст объявления')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
